export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_GET_TOKEN = 'AUTHENTICATION_GET_TOKEN';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

export const SAVE_PROVIDER_REQUEST = 'SAVE_PROVIDER_REQUEST';
export const SAVE_PROVIDER_SUCCESS = 'SAVE_PROVIDER_SUCCESS';
export const SAVE_PROVIDER_FAILURE = 'SAVE_PROVIDER_FAILURE';

export const LOAD_PROVIDERS_REQUEST = 'LOAD_PROVIDERS_REQUEST';
export const LOAD_PROVIDERS_SUCCESS = 'LOAD_PROVIDERS_SUCCESS';
export const LOAD_PROVIDERS_FAILURE = 'LOAD_PROVIDERS_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";